export const FETCH_ADVERTISEMENTS_REQUEST='FETCH_ADVERTISEMENTS_REQUEST'
export const FETCH_ADVERTISEMENTS_SUCCESS='FETCH_ADVERTISEMENTS_SUCCESS'
export const FETCH_ADVERTISEMENTS_FAIL='FETCH_ADVERTISEMENTS_FAIL'


export const ADD_ADVERTISEMENT_REQUEST = 'ADD_ADVERTISEMENT_REQUEST';
export const ADD_ADVERTISEMENT_SUCCESS = 'ADD_ADVERTISEMENT_SUCCESS';
export const ADD_ADVERTISEMENT_FAIL = 'ADD_ADVERTISEMENT_FAIL';

export const EDIT_ADVERTISEMENT_REQUEST = 'EDIT_ADVERTISEMENT_REQUEST';
export const EDIT_ADVERTISEMENT_SUCCESS = 'EDIT_ADVERTISEMENT_SUCCESS';
export const EDIT_ADVERTISEMENT_FAIL = 'EDIT_ADVERTISEMENT_FAIL';

export const DELETE_ADVERTISEMENT_REQUEST = 'DELETE_ADVERTISEMENT_REQUEST';
export const DELETE_ADVERTISEMENT_SUCCESS = 'DELETE_ADVERTISEMENT_SUCCESS';
export const DELETE_ADVERTISEMENT_FAIL = 'DELETE_ADVERTISEMENT_FAIL';
