// Fetch all API keys
export const FETCH_API_KEYS_REQUEST = 'FETCH_API_KEYS_REQUEST';
export const FETCH_API_KEYS_SUCCESS = 'FETCH_API_KEYS_SUCCESS';
export const FETCH_API_KEYS_FAIL = 'FETCH_API_KEYS_FAIL';

// Fetch single API key by ID
export const FETCH_API_KEY_REQUEST = 'FETCH_API_KEY_REQUEST';
export const FETCH_API_KEY_SUCCESS = 'FETCH_API_KEY_SUCCESS';
export const FETCH_API_KEY_FAIL = 'FETCH_API_KEY_FAIL';

// Create API key
export const CREATE_API_KEY_REQUEST = 'CREATE_API_KEY_REQUEST';
export const CREATE_API_KEY_SUCCESS = 'CREATE_API_KEY_SUCCESS';
export const CREATE_API_KEY_FAIL = 'CREATE_API_KEY_FAIL';

// Update API key
export const UPDATE_API_KEY_REQUEST = 'UPDATE_API_KEY_REQUEST';
export const UPDATE_API_KEY_SUCCESS = 'UPDATE_API_KEY_SUCCESS';
export const UPDATE_API_KEY_FAIL = 'UPDATE_API_KEY_FAIL';

// Delete API key
export const DELETE_API_KEY_REQUEST = 'DELETE_API_KEY_REQUEST';
export const DELETE_API_KEY_SUCCESS = 'DELETE_API_KEY_SUCCESS';
export const DELETE_API_KEY_FAIL = 'DELETE_API_KEY_FAIL';

// Toggle API key status (activate/deactivate)
export const TOGGLE_API_KEY_REQUEST = 'TOGGLE_API_KEY_REQUEST';
export const TOGGLE_API_KEY_SUCCESS = 'TOGGLE_API_KEY_SUCCESS';
export const TOGGLE_API_KEY_FAIL = 'TOGGLE_API_KEY_FAIL';

// Regenerate API key
export const REGENERATE_API_KEY_REQUEST = 'REGENERATE_API_KEY_REQUEST';
export const REGENERATE_API_KEY_SUCCESS = 'REGENERATE_API_KEY_SUCCESS';
export const REGENERATE_API_KEY_FAIL = 'REGENERATE_API_KEY_FAIL';
