// constants/appSettingsConstants.ts
export const FETCH_APP_SETTINGS_REQUEST = 'FETCH_APP_SETTINGS_REQUEST';
export const FETCH_APP_SETTINGS_SUCCESS = 'FETCH_APP_SETTINGS_SUCCESS';
export const FETCH_APP_SETTINGS_FAIL = 'FETCH_APP_SETTINGS_FAIL';

export const UPDATE_APP_SETTINGS_REQUEST = 'UPDATE_APP_SETTINGS_REQUEST';
export const UPDATE_APP_SETTINGS_SUCCESS = 'UPDATE_APP_SETTINGS_SUCCESS';
export const UPDATE_APP_SETTINGS_FAIL = 'UPDATE_APP_SETTINGS_FAIL';

export const RESET_APP_SETTINGS_REQUEST = 'RESET_APP_SETTINGS_REQUEST';
export const RESET_APP_SETTINGS_SUCCESS = 'RESET_APP_SETTINGS_SUCCESS';
export const RESET_APP_SETTINGS_FAIL = 'RESET_APP_SETTINGS_FAIL';
