export const FETCH_BALANCES_REQUEST='FETCH_BALANCES_REQUEST'
export const FETCH_BALANCES_SUCCESS='FETCH_BALANCES_SUCCESS'
export const FETCH_BALANCES_FAIL='FETCH_BALANCES_FAIL'


export const ADD_BALANCE_REQUEST = 'ADD_BALANCE_REQUEST';
export const ADD_BALANCE_SUCCESS = 'ADD_BALANCE_SUCCESS';
export const ADD_BALANCE_FAIL = 'ADD_BALANCE_FAIL';

export const EDIT_BALANCE_REQUEST = 'EDIT_BALANCE_REQUEST';
export const EDIT_BALANCE_SUCCESS = 'EDIT_BALANCE_SUCCESS';
export const EDIT_BALANCE_FAIL = 'EDIT_BALANCE_FAIL';

export const DELETE_BALANCE_REQUEST = 'DELETE_BALANCE_REQUEST';
export const DELETE_BALANCE_SUCCESS = 'DELETE_BALANCE_SUCCESS';
export const DELETE_BALANCE_FAIL = 'DELETE_BALANCE_FAIL';



export const ROLLBACK_BALANCE_REQUEST = 'ROLLBACK_BALANCE_REQUEST';
export const ROLLBACK_BALANCE_SUCCESS = 'ROLLBACK_BALANCE_SUCCESS';
export const ROLLBACK_BALANCE_FAIL = 'ROLLBACK_BALANCE_FAIL';


export const VERIFY_BALANCE_REQUEST = 'VERIFY_BALANCE_REQUEST';
export const VERIFY_BALANCE_SUCCESS = 'VERIFY_BALANCE_SUCCESS';
export const VERIFY_BALANCE_FAIL = 'VERIFY_BALANCE_FAIL';


export const REJECT_BALANCE_REQUEST = 'REJECT_BALANCE_REQUEST';
export const REJECT_BALANCE_SUCCESS = 'REJECT_BALANCE_SUCCESS';
export const REJECT_BALANCE_FAIL = 'REJECT_BALANCE_FAIL';
