export const FETCH_BUNDLE_LIST_REQUEST='FETCH_BUNDLE_LIST_REQUEST'
export const FETCH_BUNDLE_LIST_SUCCESS='FETCH_BUNDLE_LIST_SUCCESS'
export const FETCH_BUNDLE_LIST_FAIL='FETCH_BUNDLE_LIST_FAIL'


export const DELETE_BUNDLE_REQUEST = "DELETE_BUNDLE_REQUEST";
export const DELETE_BUNDLE_SUCCESS = "DELETE_BUNDLE_SUCCESS";
export const DELETE_BUNDLE_FAIL = "DELETE_BUNDLE_FAIL";


export const ADD_BUNDLE_REQUEST = 'ADD_BUNDLE_REQUEST';
export const ADD_BUNDLE_SUCCESS = 'ADD_BUNDLE_SUCCESS';
export const ADD_BUNDLE_FAIL = 'ADD_BUNDLE_FAIL';


export const EDIT_BUNDLE_REQUEST = 'EDIT_BUNDLE_REQUEST';
export const EDIT_BUNDLE_SUCCESS = 'EDIT_BUNDLE_SUCCESS';
export const EDIT_BUNDLE_FAIL = 'EDIT_BUNDLE_FAIL';

export const SET_PROVIDER_REQUEST = 'SET_PROVIDER_REQUEST';
export const SET_PROVIDER_SUCCESS = 'SET_PROVIDER_SUCCESS';
export const SET_PROVIDER_FAIL = 'SET_PROVIDER_FAIL';

export const UNSET_PROVIDER_REQUEST = 'UNSET_PROVIDER_REQUEST';
export const UNSET_PROVIDER_SUCCESS = 'UNSET_PROVIDER_SUCCESS';
export const UNSET_PROVIDER_FAIL = 'UNSET_PROVIDER_FAIL';


export const BUNDLE_PRICE_ADJUSTMENT_PREVIEW_REQUEST = 'BUNDLE_PRICE_ADJUSTMENT_PREVIEW_REQUEST';
export const BUNDLE_PRICE_ADJUSTMENT_PREVIEW_SUCCESS = 'BUNDLE_PRICE_ADJUSTMENT_PREVIEW_SUCCESS';
export const BUNDLE_PRICE_ADJUSTMENT_PREVIEW_FAIL = 'BUNDLE_PRICE_ADJUSTMENT_PREVIEW_FAIL';

export const BUNDLE_PRICE_ADJUSTMENT_UPDATE_REQUEST = 'BUNDLE_PRICE_ADJUSTMENT_UPDATE_REQUEST';
export const BUNDLE_PRICE_ADJUSTMENT_UPDATE_SUCCESS = 'BUNDLE_PRICE_ADJUSTMENT_UPDATE_SUCCESS';
export const BUNDLE_PRICE_ADJUSTMENT_UPDATE_FAIL = 'BUNDLE_PRICE_ADJUSTMENT_UPDATE_FAIL';


export const BULK_BUNDLE_PRICE_UPDATE_REQUEST = 'BULK_BUNDLE_PRICE_UPDATE_REQUEST';
export const BULK_BUNDLE_PRICE_UPDATE_SUCCESS = 'BULK_BUNDLE_PRICE_UPDATE_SUCCESS';
export const BULK_BUNDLE_PRICE_UPDATE_FAIL = 'BULK_BUNDLE_PRICE_UPDATE_FAIL';

export const CLEAR_PRICE_ADJUSTMENT_PREVIEW = 'CLEAR_PRICE_ADJUSTMENT_PREVIEW';
