export const FETCH_COMPANY_CODE_LIST_REQUEST='FETCH_COMPANY_CODE_LIST_REQUEST'
export const FETCH_COMPANY_CODE_LIST_SUCCESS='FETCH_COMPANY_CODE_LIST_SUCCESS'
export const FETCH_COMPANY_CODE_LIST_FAIL='FETCH_COMPANY_CODE_LIST_FAIL'


export const DELETE_COMPANY_CODE_REQUEST = "DELETE_COMPANY_CODE_REQUEST";
export const DELETE_COMPANY_CODE_SUCCESS = "DELETE_COMPANY_CODE_SUCCESS";
export const DELETE_COMPANY_CODE_FAIL = "DELETE_COMPANY_CODE_FAIL";


export const ADD_COMPANY_CODE_REQUEST = 'ADD_COMPANY_CODE_REQUEST';
export const ADD_COMPANY_CODE_SUCCESS = 'ADD_COMPANY_CODE_SUCCESS';
export const ADD_COMPANY_CODE_FAIL = 'ADD_COMPANY_CODE_FAIL';


export const EDIT_COMPANY_CODE_REQUEST = 'EDIT_COMPANY_CODE_REQUEST';
export const EDIT_COMPANY_CODE_SUCCESS = 'EDIT_COMPANY_CODE_SUCCESS';
export const EDIT_COMPANY_CODE_FAIL = 'EDIT_COMPANY_CODE_FAIL';

