export const FETCH_COUNTRIES_REQUEST='FETCH_COUNTRIES_REQUEST'
export const FETCH_COUNTRIES_SUCCESS='FETCH_COUNTRIES_SUCCESS'
export const FETCH_COUNTRIES_FAIL='FETCH_COUNTRIES_FAIL'


export const ADD_COUNTRY_REQUEST = 'ADD_COUNTRY_REQUEST';
export const ADD_COUNTRY_SUCCESS = 'ADD_COUNTRY_SUCCESS';
export const ADD_COUNTRY_FAIL = 'ADD_COUNTRY_FAIL';

export const EDIT_COUNTRY_REQUEST = 'EDIT_COUNTRY_REQUEST';
export const EDIT_COUNTRY_SUCCESS = 'EDIT_COUNTRY_SUCCESS';
export const EDIT_COUNTRY_FAIL = 'EDIT_COUNTRY_FAIL';

export const DELETE_COUNTRY_REQUEST = 'DELETE_COUNTRY_REQUEST';
export const DELETE_COUNTRY_SUCCESS = 'DELETE_COUNTRY_SUCCESS';
export const DELETE_COUNTRY_FAIL = 'DELETE_COUNTRY_FAIL';
