export const FETCH_CURRENCIES_REQUEST='FETCH_CURRENCIES_REQUEST'
export const FETCH_CURRENCIES_SUCCESS='FETCH_CURRENCIES_SUCCESS'
export const FETCH_CURRENCIES_FAILURE='FETCH_CURRENCIES_FAILURE'


export const ADD_CURRENCY_REQUEST = 'ADD_CURRENCY_REQUEST';
export const ADD_CURRENCY_SUCCESS = 'ADD_CURRENCY_SUCCESS';
export const ADD_CURRENCY_FAIL = 'ADD_CURRENCY_FAIL';

export const EDIT_CURRENCY_REQUEST = 'EDIT_CURRENCY_REQUEST';
export const EDIT_CURRENCY_SUCCESS = 'EDIT_CURRENCY_SUCCESS';
export const EDIT_CURRENCY_FAIL = 'EDIT_CURRENCY_FAIL';

export const DELETE_CURRENCY_REQUEST = 'DELETE_CURRENCY_REQUEST';
export const DELETE_CURRENCY_SUCCESS = 'DELETE_CURRENCY_SUCCESS';
export const DELETE_CURRENCY_FAIL = 'DELETE_CURRENCY_FAIL';
