export const FETCH_DISTRICTS_REQUEST='FETCH_DISTRICTS_REQUEST'
export const FETCH_DISTRICTS_SUCCESS='FETCH_DISTRICTS_SUCCESS'
export const FETCH_DISTRICTS_FAIL='FETCH_DISTRICTS_FAIL'


export const ADD_DISTRICT_REQUEST = 'ADD_DISTRICT_REQUEST';
export const ADD_DISTRICT_SUCCESS = 'ADD_DISTRICT_SUCCESS';
export const ADD_DISTRICT_FAIL = 'ADD_DISTRICT_FAIL';

export const EDIT_DISTRICT_REQUEST = 'EDIT_DISTRICT_REQUEST';
export const EDIT_DISTRICT_SUCCESS = 'EDIT_DISTRICT_SUCCESS';
export const EDIT_DISTRICT_FAIL = 'EDIT_DISTRICT_FAIL';

export const DELETE_DISTRICT_REQUEST = 'DELETE_DISTRICT_REQUEST';
export const DELETE_DISTRICT_SUCCESS = 'DELETE_DISTRICT_SUCCESS';
export const DELETE_DISTRICT_FAIL = 'DELETE_DISTRICT_FAIL';
