export const FETCH_EARNING_BALANCE_LIST_REQUEST='FETCH_EARNING_BALANCE_LIST_REQUEST'
export const FETCH_EARNING_BALANCE_LIST_SUCCESS='FETCH_EARNING_BALANCE_LIST_SUCCESS'
export const FETCH_EARNING_BALANCE_LIST_FAIL='FETCH_EARNING_BALANCE_LIST_FAIL'



export const ADD_EARNING_BALANCE_REQUEST = 'ADD_EARNING_BALANCE_REQUEST';
export const ADD_EARNING_BALANCE_SUCCESS = 'ADD_EARNING_BALANCE_SUCCESS';
export const ADD_EARNING_BALANCE_FAIL = 'ADD_EARNING_BALANCE_FAIL';


export const CHANGE_STATUS_EARNING_BALANCE_REQUEST = 'CHANGE_STATUS_EARNING_BALANCE_REQUEST';
export const CHANGE_STATUS_EARNING_BALANCE_SUCCESS = 'CHANGE_STATUS_EARNING_BALANCE_SUCCESS';
export const CHANGE_STATUS_EARNING_BALANCE_FAIL = 'CHANGE_STATUS_EARNING_BALANCE_FAIL';

