export const FETCH_GROUP_PRICING_LIST_REQUEST='FETCH_GROUP_PRICING_LIST_REQUEST'
export const FETCH_GROUP_PRICING_LIST_SUCCESS='FETCH_GROUP_PRICING_LIST_SUCCESS'
export const FETCH_GROUP_PRICING_LIST_FAIL='FETCH_GROUP_PRICING_LIST_FAIL'


export const DELETE_GROUP_PRICING_REQUEST = "DELETE_GROUP_PRICING_REQUEST";
export const DELETE_GROUP_PRICING_SUCCESS = "DELETE_GROUP_PRICING_SUCCESS";
export const DELETE_GROUP_PRICING_FAIL = "DELETE_GROUP_PRICING_FAIL";


export const ADD_GROUP_PRICING_REQUEST = 'ADD_GROUP_PRICING_REQUEST';
export const ADD_GROUP_PRICING_SUCCESS = 'ADD_GROUP_PRICING_SUCCESS';
export const ADD_GROUP_PRICING_FAIL = 'ADD_GROUP_PRICING_FAIL';


export const EDIT_GROUP_PRICING_REQUEST = 'EDIT_GROUP_PRICING_REQUEST';
export const EDIT_GROUP_PRICING_SUCCESS = 'EDIT_GROUP_PRICING_SUCCESS';
export const EDIT_GROUP_PRICING_FAIL = 'EDIT_GROUP_PRICING_FAIL';

