export const FETCH_GROUP_DISCOUNTS_REQUEST='FETCH_GROUP_DISCOUNTS_REQUEST'
export const FETCH_GROUP_DISCOUNTS_SUCCESS='FETCH_GROUP_DISCOUNTS_SUCCESS'
export const FETCH_GROUP_DISCOUNTS_FAIL='FETCH_GROUP_DISCOUNTS_FAIL'


export const ADD_GROUP_DISCOUNT_REQUEST = 'ADD_GROUP_DISCOUNT_REQUEST';
export const ADD_GROUP_DISCOUNT_SUCCESS = 'ADD_GROUP_DISCOUNT_SUCCESS';
export const ADD_GROUP_DISCOUNT_FAIL = 'ADD_GROUP_DISCOUNT_FAIL';

export const EDIT_GROUP_DISCOUNT_REQUEST = 'EDIT_GROUP_DISCOUNT_REQUEST';
export const EDIT_GROUP_DISCOUNT_SUCCESS = 'EDIT_GROUP_DISCOUNT_SUCCESS';
export const EDIT_GROUP_DISCOUNT_FAIL = 'EDIT_GROUP_DISCOUNT_FAIL';

export const DELETE_GROUP_DISCOUNT_REQUEST = 'DELETE_GROUP_DISCOUNT_REQUEST';
export const DELETE_GROUP_DISCOUNT_SUCCESS = 'DELETE_GROUP_DISCOUNT_SUCCESS';
export const DELETE_GROUP_DISCOUNT_FAIL = 'DELETE_GROUP_DISCOUNT_FAIL';
