export const FETCH_HAWALA_LIST_REQUEST='FETCH_HAWALA_LIST_REQUEST'
export const FETCH_HAWALA_LIST_SUCCESS='FETCH_HAWALA_LIST_SUCCESS'
export const FETCH_HAWALA_LIST_FAIL='FETCH_HAWALA_LIST_FAIL'


export const DELETE_HAWALA_REQUEST = "DELETE_HAWALA_REQUEST";
export const DELETE_HAWALA_SUCCESS = "DELETE_HAWALA_SUCCESS";
export const DELETE_HAWALA_FAIL = "DELETE_HAWALA_FAIL";


export const ADD_HAWALA_REQUEST = 'ADD_HAWALA_REQUEST';
export const ADD_HAWALA_SUCCESS = 'ADD_HAWALA_SUCCESS';
export const ADD_HAWALA_FAIL = 'ADD_HAWALA_FAIL';


export const EDIT_HAWALA_REQUEST = 'EDIT_HAWALA_REQUEST';
export const EDIT_HAWALA_SUCCESS = 'EDIT_HAWALA_SUCCESS';
export const EDIT_HAWALA_FAIL = 'EDIT_HAWALA_FAIL';


export const CHANGE_HAWALA_STATUS_REQUEST = 'CHANGE_HAWALA_STATUS_REQUEST';
export const CHANGE_HAWALA_STATUS_SUCCESS = 'CHANGE_HAWALA_STATUS_SUCCESS';
export const CHANGE_HAWALA_STATUS_FAIL = 'CHANGE_HAWALA_STATUS_FAIL';

