export const FETCH_HAWALA_CURRENCIES_REQUEST='FETCH_HAWALA_CURRENCIES_REQUEST'
export const FETCH_HAWALA_CURRENCIES_SUCCESS='FETCH_HAWALA_CURRENCIES_SUCCESS'
export const FETCH_HAWALA_CURRENCIES_FAILURE='FETCH_HAWALA_CURRENCIES_FAILURE'


export const ADD_HAWALA_CURRENCY_REQUEST = 'ADD_HAWALA_CURRENCY_REQUEST';
export const ADD_HAWALA_CURRENCY_SUCCESS = 'ADD_HAWALA_CURRENCY_SUCCESS';
export const ADD_HAWALA_CURRENCY_FAIL = 'ADD_HAWALA_CURRENCY_FAIL';

export const EDIT_HAWALA_CURRENCY_REQUEST = 'EDIT_HAWALA_CURRENCY_REQUEST';
export const EDIT_HAWALA_CURRENCY_SUCCESS = 'EDIT_HAWALA_CURRENCY_SUCCESS';
export const EDIT_HAWALA_CURRENCY_FAIL = 'EDIT_HAWALA_CURRENCY_FAIL';

export const DELETE_HAWALA_CURRENCY_REQUEST = 'DELETE_HAWALA_CURRENCY_REQUEST';
export const DELETE_HAWALA_CURRENCY_SUCCESS = 'DELETE_HAWALA_CURRENCY_SUCCESS';
export const DELETE_HAWALA_CURRENCY_FAIL = 'DELETE_HAWALA_CURRENCY_FAIL';
