export const FETCH_HAWALA_BRANCH_LIST_REQUEST='FETCH_HAWALA_BRANCH_LIST_REQUEST'
export const FETCH_HAWALA_BRANCH_LIST_SUCCESS='FETCH_HAWALA_BRANCH_LIST_SUCCESS'
export const FETCH_HAWALA_BRANCH_LIST_FAIL='FETCH_HAWALA_BRANCH_LIST_FAIL'


export const DELETE_HAWALA_BRANCH_REQUEST = "DELETE_HAWALA_BRANCH_REQUEST";
export const DELETE_HAWALA_BRANCH_SUCCESS = "DELETE_HAWALA_BRANCH_SUCCESS";
export const DELETE_HAWALA_BRANCH_FAIL = "DELETE_HAWALA_BRANCH_FAIL";


export const ADD_HAWALA_BRANCH_REQUEST = 'ADD_HAWALA_BRANCH_REQUEST';
export const ADD_HAWALA_BRANCH_SUCCESS = 'ADD_HAWALA_BRANCH_SUCCESS';
export const ADD_HAWALA_BRANCH_FAIL = 'ADD_HAWALA_BRANCH_FAIL';


export const EDIT_HAWALA_BRANCH_REQUEST = 'EDIT_HAWALA_BRANCH_REQUEST';
export const EDIT_HAWALA_BRANCH_SUCCESS = 'EDIT_HAWALA_BRANCH_SUCCESS';
export const EDIT_HAWALA_BRANCH_FAIL = 'EDIT_HAWALA_BRANCH_FAIL';

