export const FETCH_HELP_ARTICLES_REQUEST='FETCH_HELP_ARTICLES_REQUEST'
export const FETCH_HELP_ARTICLES_SUCCESS='FETCH_HELP_ARTICLES_SUCCESS'
export const FETCH_HELP_ARTICLES_FAILURE='FETCH_HELP_ARTICLES_FAILURE'


export const ADD_HELP_ARTICLE_REQUEST = 'ADD_HELP_ARTICLE_REQUEST';
export const ADD_HELP_ARTICLE_SUCCESS = 'ADD_HELP_ARTICLE_SUCCESS';
export const ADD_HELP_ARTICLE_FAIL = 'ADD_HELP_ARTICLE_FAIL';

export const EDIT_HELP_ARTICLE_REQUEST = 'EDIT_HELP_ARTICLE_REQUEST';
export const EDIT_HELP_ARTICLE_SUCCESS = 'EDIT_HELP_ARTICLE_SUCCESS';
export const EDIT_HELP_ARTICLE_FAIL = 'EDIT_HELP_ARTICLE_FAIL';

export const DELETE_HELP_ARTICLE_REQUEST = 'DELETE_HELP_ARTICLE_REQUEST';
export const DELETE_HELP_ARTICLE_SUCCESS = 'DELETE_HELP_ARTICLE_SUCCESS';
export const DELETE_HELP_ARTICLE_FAIL = 'DELETE_HELP_ARTICLE_FAIL';
