export const FETCH_LANGUAGES_REQUEST='FETCH_LANGUAGES_REQUEST'
export const FETCH_LANGUAGES_SUCCESS='FETCH_LANGUAGES_SUCCESS'
export const FETCH_LANGUAGES_FAIL='FETCH_LANGUAGES_FAIL'


export const ADD_LANGUAGE_REQUEST = 'ADD_LANGUAGE_REQUEST';
export const ADD_LANGUAGE_SUCCESS = 'ADD_LANGUAGE_SUCCESS';
export const ADD_LANGUAGE_FAIL = 'ADD_LANGUAGE_FAIL';

export const EDIT_LANGUAGE_REQUEST = 'EDIT_LANGUAGE_REQUEST';
export const EDIT_LANGUAGE_SUCCESS = 'EDIT_LANGUAGE_SUCCESS';
export const EDIT_LANGUAGE_FAIL = 'EDIT_LANGUAGE_FAIL';

export const DELETE_LANGUAGE_REQUEST = 'DELETE_LANGUAGE_REQUEST';
export const DELETE_LANGUAGE_SUCCESS = 'DELETE_LANGUAGE_SUCCESS';
export const DELETE_LANGUAGE_FAIL = 'DELETE_LANGUAGE_FAIL';
