export const FETCH_MONEY_TRANSACTIONS_LIST_REQUEST='FETCH_MONEY_TRANSACTIONS_LIST_REQUEST'
export const FETCH_MONEY_TRANSACTIONS_LIST_SUCCESS='FETCH_MONEY_TRANSACTIONS_LIST_SUCCESS'
export const FETCH_MONEY_TRANSACTIONS_LIST_FAIL='FETCH_MONEY_TRANSACTIONS_LIST_FAIL'


export const DELETE_MONEY_TRANSACTIONS_REQUEST = "DELETE_MONEY_TRANSACTIONS_REQUEST";
export const DELETE_MONEY_TRANSACTIONS_SUCCESS = "DELETE_MONEY_TRANSACTIONS_SUCCESS";
export const DELETE_MONEY_TRANSACTIONS_FAIL = "DELETE_MONEY_TRANSACTIONS_FAIL";


export const ADD_MONEY_TRANSACTIONS_REQUEST = 'ADD_MONEY_TRANSACTIONS_REQUEST';
export const ADD_MONEY_TRANSACTIONS_SUCCESS = 'ADD_MONEY_TRANSACTIONS_SUCCESS';
export const ADD_MONEY_TRANSACTIONS_FAIL = 'ADD_MONEY_TRANSACTIONS_FAIL';


export const EDIT_MONEY_TRANSACTIONS_REQUEST = 'EDIT_MONEY_TRANSACTIONS_REQUEST';
export const EDIT_MONEY_TRANSACTIONS_SUCCESS = 'EDIT_MONEY_TRANSACTIONS_SUCCESS';
export const EDIT_MONEY_TRANSACTIONS_FAIL = 'EDIT_MONEY_TRANSACTIONS_FAIL';

