export const FETCH_PAYMENT_LIST_REQUEST='FETCH_PAYMENT_LIST_REQUEST'
export const FETCH_PAYMENT_LIST_SUCCESS='FETCH_PAYMENT_LIST_SUCCESS'
export const FETCH_PAYMENT_LIST_FAIL='FETCH_PAYMENT_LIST_FAIL'


export const DELETE_PAYMENT_REQUEST = "DELETE_PAYMENT_REQUEST";
export const DELETE_PAYMENT_SUCCESS = "DELETE_PAYMENT_SUCCESS";
export const DELETE_PAYMENT_FAIL = "DELETE_PAYMENT_FAIL";


export const ADD_PAYMENT_REQUEST = 'ADD_PAYMENT_REQUEST';
export const ADD_PAYMENT_SUCCESS = 'ADD_PAYMENT_SUCCESS';
export const ADD_PAYMENT_FAIL = 'ADD_PAYMENT_FAIL';


export const EDIT_PAYMENT_REQUEST = 'EDIT_PAYMENT_REQUEST';
export const EDIT_PAYMENT_SUCCESS = 'EDIT_PAYMENT_SUCCESS';
export const EDIT_PAYMENT_FAIL = 'EDIT_PAYMENT_FAIL';


export const ROLLBACK_PAYMENT_REQUEST = 'ROLLBACK_PAYMENT_REQUEST';
export const ROLLBACK_PAYMENT_SUCCESS = 'ROLLBACK_PAYMENT_SUCCESS';
export const ROLLBACK_PAYMENT_FAIL = 'ROLLBACK_PAYMENT_FAIL';


export const INVALIDATE_PAYMENT_REQUEST = 'INVALIDATE_PAYMENT_REQUEST';
export const INVALIDATE_PAYMENT_SUCCESS = 'INVALIDATE_PAYMENT_SUCCESS';
export const INVALIDATE_PAYMENT_FAIL = 'INVALIDATE_PAYMENT_FAIL';

export const VERIFY_PAYMENT_REQUEST = 'VERIFY_PAYMENT_REQUEST';
export const VERIFY_PAYMENT_SUCCESS = 'VERIFY_PAYMENT_SUCCESS';
export const VERIFY_PAYMENT_FAIL = 'VERIFY_PAYMENT_FAIL';


export const VERIFY_PAYMENT_AND_SEND_TO_BALANCE_REQUEST = 'VERIFY_PAYMENT_AND_SEND_TO_BALANCE_REQUEST';
export const VERIFY_PAYMENT_AND_SEND_TO_BALANCE_SUCCESS = 'VERIFY_PAYMENT_AND_SEND_TO_BALANCE_SUCCESS';
export const VERIFY_PAYMENT_AND_SEND_TO_BALANCE_FAIL = 'VERIFY_PAYMENT_AND_SEND_TO_BALANCE_FAIL';
