export const FETCH_PAYMENT_TYPE_LIST_REQUEST='FETCH_PAYMENT_TYPE_LIST_REQUEST'
export const FETCH_PAYMENT_TYPE_LIST_SUCCESS='FETCH_PAYMENT_TYPE_LIST_SUCCESS'
export const FETCH_PAYMENT_TYPE_LIST_FAIL='FETCH_PAYMENT_TYPE_LIST_FAIL'


export const DELETE_PAYMENT_TYPE_REQUEST = "DELETE_PAYMENT_TYPE_REQUEST";
export const DELETE_PAYMENT_TYPE_SUCCESS = "DELETE_PAYMENT_TYPE_SUCCESS";
export const DELETE_PAYMENT_TYPE_FAIL = "DELETE_PAYMENT_TYPE_FAIL";


export const ADD_PAYMENT_TYPE_REQUEST = 'ADD_PAYMENT_TYPE_REQUEST';
export const ADD_PAYMENT_TYPE_SUCCESS = 'ADD_PAYMENT_TYPE_SUCCESS';
export const ADD_PAYMENT_TYPE_FAIL = 'ADD_PAYMENT_TYPE_FAIL';


export const EDIT_PAYMENT_TYPE_REQUEST = 'EDIT_PAYMENT_TYPE_REQUEST';
export const EDIT_PAYMENT_TYPE_SUCCESS = 'EDIT_PAYMENT_TYPE_SUCCESS';
export const EDIT_PAYMENT_TYPE_FAIL = 'EDIT_PAYMENT_TYPE_FAIL';

