export const FETCH_PAYMENT_METHOD_LIST_REQUEST='FETCH_PAYMENT_METHOD_LIST_REQUEST'
export const FETCH_PAYMENT_METHOD_LIST_SUCCESS='FETCH_PAYMENT_METHOD_LIST_SUCCESS'
export const FETCH_PAYMENT_METHOD_LIST_FAIL='FETCH_PAYMENT_METHOD_LIST_FAIL'


export const DELETE_PAYMENT_METHOD_REQUEST = "DELETE_PAYMENT_METHOD_REQUEST";
export const DELETE_PAYMENT_METHOD_SUCCESS = "DELETE_PAYMENT_METHOD_SUCCESS";
export const DELETE_PAYMENT_METHOD_FAIL = "DELETE_PAYMENT_METHOD_FAIL";


export const ADD_PAYMENT_METHOD_REQUEST = 'ADD_PAYMENT_METHOD_REQUEST';
export const ADD_PAYMENT_METHOD_SUCCESS = 'ADD_PAYMENT_METHOD_SUCCESS';
export const ADD_PAYMENT_METHOD_FAIL = 'ADD_PAYMENT_METHOD_FAIL';


export const EDIT_PAYMENT_METHOD_REQUEST = 'EDIT_PAYMENT_METHOD_REQUEST';
export const EDIT_PAYMENT_METHOD_SUCCESS = 'EDIT_PAYMENT_METHOD_SUCCESS';
export const EDIT_PAYMENT_METHOD_FAIL = 'EDIT_PAYMENT_METHOD_FAIL';

