export const FETCH_PROVIDERS_REQUEST='FETCH_PROVIDERS_REQUEST'
export const FETCH_PROVIDERS_SUCCESS='FETCH_PROVIDERS_SUCCESS'
export const FETCH_PROVIDERS_FAIL='FETCH_PROVIDERS_FAIL'


export const ADD_PROVIDER_REQUEST = 'ADD_PROVIDER_REQUEST';
export const ADD_PROVIDER_SUCCESS = 'ADD_PROVIDER_SUCCESS';
export const ADD_PROVIDER_FAIL = 'ADD_PROVIDER_FAIL';

export const EDIT_PROVIDER_REQUEST = 'EDIT_PROVIDER_REQUEST';
export const EDIT_PROVIDER_SUCCESS = 'EDIT_PROVIDER_SUCCESS';
export const EDIT_PROVIDER_FAIL = 'EDIT_PROVIDER_FAIL';

export const DELETE_PROVIDER_REQUEST = 'DELETE_PROVIDER_REQUEST';
export const DELETE_PROVIDER_SUCCESS = 'DELETE_PROVIDER_SUCCESS';
export const DELETE_PROVIDER_FAIL = 'DELETE_PROVIDER_FAIL';


export const TOGGLE_PROVIDER_REQUEST = 'TOGGLE_PROVIDER_REQUEST';
export const TOGGLE_PROVIDER_SUCCESS = 'TOGGLE_PROVIDER_SUCCESS';
export const TOGGLE_PROVIDER_FAIL = 'TOGGLE_PROVIDER_FAIL';
