// app/redux/constants/providerInfoReducer.ts
export const FETCH_PROVIDER_INFO_REQUEST = 'FETCH_PROVIDER_INFO_REQUEST';
export const FETCH_PROVIDER_INFO_SUCCESS = 'FETCH_PROVIDER_INFO_SUCCESS';
export const FETCH_PROVIDER_INFO_FAIL = 'FETCH_PROVIDER_INFO_FAIL';