export const FETCH_PROVINCES_REQUEST = 'FETCH_PROVINCES_REQUEST';
export const FETCH_PROVINCES_SUCCESS = 'FETCH_PROVINCES_SUCCESS';
export const FETCH_PROVINCES_FAIL = 'FETCH_PROVINCES_FAIL';

export const ADD_PROVINCE_REQUEST = 'ADD_PROVINCE_REQUEST';
export const ADD_PROVINCE_SUCCESS = 'ADD_PROVINCE_SUCCESS';
export const ADD_PROVINCE_FAIL = 'ADD_PROVINCE_FAIL';

export const EDIT_PROVINCE_REQUEST = 'EDIT_PROVINCE_REQUEST';
export const EDIT_PROVINCE_SUCCESS = 'EDIT_PROVINCE_SUCCESS';
export const EDIT_PROVINCE_FAIL = 'EDIT_PROVINCE_FAIL';

export const DELETE_PROVINCE_REQUEST = 'DELETE_PROVINCE_REQUEST';
export const DELETE_PROVINCE_SUCCESS = 'DELETE_PROVINCE_SUCCESS';
export const DELETE_PROVINCE_FAIL = 'DELETE_PROVINCE_FAIL';
