export const FETCH_PURCHASED_PRODUCTS_REQUEST = 'FETCH_PURCHASED_PRODUCTS_REQUEST';
export const FETCH_PURCHASED_PRODUCTS_SUCCESS = 'FETCH_PURCHASED_PRODUCTS_SUCCESS';
export const FETCH_PURCHASED_PRODUCTS_FAIL = 'FETCH_PURCHASED_PRODUCTS_FAIL';

export const ADD_PURCHASED_PRODUCT_REQUEST = 'ADD_PURCHASED_PRODUCT_REQUEST';
export const ADD_PURCHASED_PRODUCT_SUCCESS = 'ADD_PURCHASED_PRODUCT_SUCCESS';
export const ADD_PURCHASED_PRODUCT_FAIL = 'ADD_PURCHASED_PRODUCT_FAIL';

export const EDIT_PURCHASED_PRODUCT_REQUEST = 'EDIT_PURCHASED_PRODUCT_REQUEST';
export const EDIT_PURCHASED_PRODUCT_SUCCESS = 'EDIT_PURCHASED_PRODUCT_SUCCESS';
export const EDIT_PURCHASED_PRODUCT_FAIL = 'EDIT_PURCHASED_PRODUCT_FAIL';

export const DELETE_PURCHASED_PRODUCT_REQUEST = 'DELETE_PURCHASED_PRODUCT_REQUEST';
export const DELETE_PURCHASED_PRODUCT_SUCCESS = 'DELETE_PURCHASED_PRODUCT_SUCCESS';
export const DELETE_PURCHASED_PRODUCT_FAIL = 'DELETE_PURCHASED_PRODUCT_FAIL';
