export const FETCH_RESELLERS_REQUEST = 'FETCH_RESELLERS_REQUEST';
export const FETCH_RESELLERS_SUCCESS = 'FETCH_RESELLERS_SUCCESS';
export const FETCH_RESELLERS_FAIL = 'FETCH_RESELLERS_FAIL';

export const ADD_RESELLER_REQUEST = 'ADD_RESELLER_REQUEST';
export const ADD_RESELLER_SUCCESS = 'ADD_RESELLER_SUCCESS';
export const ADD_RESELLER_FAIL = 'ADD_RESELLER_FAIL';

export const EDIT_RESELLER_REQUEST = 'EDIT_RESELLER_REQUEST';
export const EDIT_RESELLER_SUCCESS = 'EDIT_RESELLER_SUCCESS';
export const EDIT_RESELLER_FAIL = 'EDIT_RESELLER_FAIL';

export const DELETE_RESELLER_REQUEST = 'DELETE_RESELLER_REQUEST';
export const DELETE_RESELLER_SUCCESS = 'DELETE_RESELLER_SUCCESS';
export const DELETE_RESELLER_FAIL = 'DELETE_RESELLER_FAIL';


export const CHANGE_RESELLER_STATUS_REQUEST = "CHANGE_RESELLER_STATUS_REQUEST";
export const CHANGE_RESELLER_STATUS_SUCCESS = "CHANGE_RESELLER_STATUS_SUCCESS";
export const CHANGE_RESELLER_STATUS_FAIL = "CHANGE_RESELLER_STATUS_FAIL";

export const GET_RESELLER_BY_ID_REQUEST = "GET_RESELLER_BY_ID_REQUEST";
export const GET_RESELLER_BY_ID_SUCCESS = "GET_RESELLER_BY_ID_SUCCESS";
export const GET_RESELLER_BY_ID_FAIL = "GET_RESELLER_BY_ID_FAIL";


export const CHANGE_RESELLER_PASSWORD_REQUEST = "CHANGE_RESELLER_PASSWORD_REQUEST";
export const CHANGE_RESELLER_PASSWORD_SUCCESS = "CHANGE_RESELLER_PASSWORD_SUCCESS";
export const CHANGE_RESELLER_PASSWORD_FAIL = "CHANGE_RESELLER_PASSWORD_FAIL";

export const CHANGE_RESELLER_PIN_REQUEST = "CHANGE_RESELLER_PIN_REQUEST";
export const CHANGE_RESELLER_PIN_SUCCESS = "CHANGE_RESELLER_PIN_SUCCESS";
export const CHANGE_RESELLER_PIN_FAIL = "CHANGE_RESELLER_PIN_FAIL";
