export const FETCH_RESELLER_GROUP_LIST_REQUEST='FETCH_RESELLER_GROUP_LIST_REQUEST'
export const FETCH_RESELLER_GROUP_LIST_SUCCESS='FETCH_RESELLER_GROUP_LIST_SUCCESS'
export const FETCH_RESELLER_GROUP_LIST_FAIL='FETCH_RESELLER_GROUP_LIST_FAIL'


export const DELETE_RESELLER_GROUP_REQUEST = "DELETE_RESELLER_GROUP_REQUEST";
export const DELETE_RESELLER_GROUP_SUCCESS = "DELETE_RESELLER_GROUP_SUCCESS";
export const DELETE_RESELLER_GROUP_FAIL = "DELETE_RESELLER_GROUP_FAIL";


export const ADD_RESELLER_GROUP_REQUEST = 'ADD_RESELLER_GROUP_REQUEST';
export const ADD_RESELLER_GROUP_SUCCESS = 'ADD_RESELLER_GROUP_SUCCESS';
export const ADD_RESELLER_GROUP_FAIL = 'ADD_RESELLER_GROUP_FAIL';


export const EDIT_RESELLER_GROUP_REQUEST = 'EDIT_RESELLER_GROUP_REQUEST';
export const EDIT_RESELLER_GROUP_SUCCESS = 'EDIT_RESELLER_GROUP_SUCCESS';
export const EDIT_RESELLER_GROUP_FAIL = 'EDIT_RESELLER_GROUP_FAIL';

