export const FETCH_ROLE_LIST_REQUEST='FETCH_ROLE_LIST_REQUEST'
export const FETCH_ROLE_LIST_SUCCESS='FETCH_ROLE_LIST_SUCCESS'
export const FETCH_ROLE_LIST_FAIL='FETCH_ROLE_LIST_FAIL'

export const FETCH_SINGLE_ROLE_REQUEST='FETCH_SINGLE_ROLE_REQUEST'
export const FETCH_SINGLE_ROLE_SUCCESS='FETCH_SINGLE_ROLE_SUCCESS'
export const FETCH_SINGLE_ROLE_FAIL='FETCH_SINGLE_ROLE_FAIL'
export const CLEAR_SINGLE_ROLE = 'CLEAR_SINGLE_ROLE';



export const DELETE_ROLE_REQUEST = "DELETE_ROLE_REQUEST";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAIL = "DELETE_ROLE_FAIL";


export const ADD_ROLE_REQUEST = 'ADD_ROLE_REQUEST';
export const ADD_ROLE_SUCCESS = 'ADD_ROLE_SUCCESS';
export const ADD_ROLE_FAIL = 'ADD_ROLE_FAIL';


export const EDIT_ROLE_REQUEST = 'EDIT_ROLE_REQUEST';
export const EDIT_ROLE_SUCCESS = 'EDIT_ROLE_SUCCESS';
export const EDIT_ROLE_FAIL = 'EDIT_ROLE_FAIL';

