// singleProviderConstants.ts
export const FETCH_SINGLE_PROVIDER_REQUEST = 'FETCH_SINGLE_PROVIDER_REQUEST';
export const FETCH_SINGLE_PROVIDER_SUCCESS = 'FETCH_SINGLE_PROVIDER_SUCCESS';
export const FETCH_SINGLE_PROVIDER_FAIL = 'FETCH_SINGLE_PROVIDER_FAIL';
export const CLEAR_SINGLE_PROVIDER = 'CLEAR_SINGLE_PROVIDER';
