export const FETCH_SUPPLIERS_REQUEST = 'FETCH_SUPPLIERS_REQUEST';
export const FETCH_SUPPLIERS_SUCCESS = 'FETCH_SUPPLIERS_SUCCESS';
export const FETCH_SUPPLIERS_FAIL = 'FETCH_SUPPLIERS_FAIL';

export const ADD_SUPPLIER_REQUEST = 'ADD_SUPPLIER_REQUEST';
export const ADD_SUPPLIER_SUCCESS = 'ADD_SUPPLIER_SUCCESS';
export const ADD_SUPPLIER_FAIL = 'ADD_SUPPLIER_FAIL';

export const EDIT_SUPPLIER_REQUEST = 'EDIT_SUPPLIER_REQUEST';
export const EDIT_SUPPLIER_SUCCESS = 'EDIT_SUPPLIER_SUCCESS';
export const EDIT_SUPPLIER_FAIL = 'EDIT_SUPPLIER_FAIL';

export const DELETE_SUPPLIER_REQUEST = 'DELETE_SUPPLIER_REQUEST';
export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS';
export const DELETE_SUPPLIER_FAIL = 'DELETE_SUPPLIER_FAIL';
