export const FETCH_SUPPORT_CONTACT_LIST_REQUEST='FETCH_SUPPORT_CONTACT_LIST_REQUEST'
export const FETCH_SUPPORT_CONTACT_LIST_SUCCESS='FETCH_SUPPORT_CONTACT_LIST_SUCCESS'
export const FETCH_SUPPORT_CONTACT_LIST_FAIL='FETCH_SUPPORT_CONTACT_LIST_FAIL'


export const DELETE_SUPPORT_CONTACT_REQUEST = "DELETE_SUPPORT_CONTACT_REQUEST";
export const DELETE_SUPPORT_CONTACT_SUCCESS = "DELETE_SUPPORT_CONTACT_SUCCESS";
export const DELETE_SUPPORT_CONTACT_FAIL = "DELETE_SUPPORT_CONTACT_FAIL";


export const ADD_SUPPORT_CONTACT_REQUEST = 'ADD_SUPPORT_CONTACT_REQUEST';
export const ADD_SUPPORT_CONTACT_SUCCESS = 'ADD_SUPPORT_CONTACT_SUCCESS';
export const ADD_SUPPORT_CONTACT_FAIL = 'ADD_SUPPORT_CONTACT_FAIL';


export const EDIT_SUPPORT_CONTACT_REQUEST = 'EDIT_SUPPORT_CONTACT_REQUEST';
export const EDIT_SUPPORT_CONTACT_SUCCESS = 'EDIT_SUPPORT_CONTACT_SUCCESS';
export const EDIT_SUPPORT_CONTACT_FAIL = 'EDIT_SUPPORT_CONTACT_FAIL';

