// Fetch Withdraw Requests
export const FETCH_WITHDRAW_REQUESTS_REQUEST = 'FETCH_WITHDRAW_REQUESTS_REQUEST';
export const FETCH_WITHDRAW_REQUESTS_SUCCESS = 'FETCH_WITHDRAW_REQUESTS_SUCCESS';
export const FETCH_WITHDRAW_REQUESTS_FAILURE = 'FETCH_WITHDRAW_REQUESTS_FAILURE';

// Create Withdraw Request
export const CREATE_WITHDRAW_REQUEST_REQUEST = 'CREATE_WITHDRAW_REQUEST_REQUEST';
export const CREATE_WITHDRAW_REQUEST_SUCCESS = 'CREATE_WITHDRAW_REQUEST_SUCCESS';
export const CREATE_WITHDRAW_REQUEST_FAILURE = 'CREATE_WITHDRAW_REQUEST_FAILURE';

// Update Withdraw Request Status
export const UPDATE_WITHDRAW_STATUS_REQUEST = 'UPDATE_WITHDRAW_STATUS_REQUEST';
export const UPDATE_WITHDRAW_STATUS_SUCCESS = 'UPDATE_WITHDRAW_STATUS_SUCCESS';
export const UPDATE_WITHDRAW_STATUS_FAILURE = 'UPDATE_WITHDRAW_STATUS_FAILURE';

// Filter constants
export const SET_WITHDRAW_FILTERS = 'SET_WITHDRAW_FILTERS';
export const CLEAR_WITHDRAW_FILTERS = 'CLEAR_WITHDRAW_FILTERS';