// Fetch Withdrawal Policies
export const FETCH_WITHDRAW_POLICIES_REQUEST = 'FETCH_WITHDRAW_POLICIES_REQUEST';
export const FETCH_WITHDRAW_POLICIES_SUCCESS = 'FETCH_WITHDRAW_POLICIES_SUCCESS';
export const FETCH_WITHDRAW_POLICIES_FAILURE = 'FETCH_WITHDRAW_POLICIES_FAILURE';

// Add Withdrawal Policy
export const ADD_WITHDRAW_POLICY_REQUEST = 'ADD_WITHDRAW_POLICY_REQUEST';
export const ADD_WITHDRAW_POLICY_SUCCESS = 'ADD_WITHDRAW_POLICY_SUCCESS';
export const ADD_WITHDRAW_POLICY_FAIL = 'ADD_WITHDRAW_POLICY_FAIL';

// Edit Withdrawal Policy
export const EDIT_WITHDRAW_POLICY_REQUEST = 'EDIT_WITHDRAW_POLICY_REQUEST';
export const EDIT_WITHDRAW_POLICY_SUCCESS = 'EDIT_WITHDRAW_POLICY_SUCCESS';
export const EDIT_WITHDRAW_POLICY_FAIL = 'EDIT_WITHDRAW_POLICY_FAIL';

// Delete Withdrawal Policy
export const DELETE_WITHDRAW_POLICY_REQUEST = 'DELETE_WITHDRAW_POLICY_REQUEST';
export const DELETE_WITHDRAW_POLICY_SUCCESS = 'DELETE_WITHDRAW_POLICY_SUCCESS';
export const DELETE_WITHDRAW_POLICY_FAIL = 'DELETE_WITHDRAW_POLICY_FAIL';